Hackathon/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name="Home"),
    url(r'^Contact-Us', views.Contact, name="Contact"),
    path('Check/', include('Heart.urls')),
]

urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Heart/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'Heart'

urlpatterns = [
    url(r'^check/$', views.Check, name="check"),
    url(r'^predict/$', views.predictHeart, name="predictHeart"),
]

Heart/models.py
from django.db import models

# Create your models here.

Hackathon/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'base.html')

def Contact(request):
    return render(request, "contact.html")

Heart/views.py
from django.shortcuts import render
from django.http import HttpResponse
import pandas as pd
from joblib import dump, load

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

def Check(request):
    #cont = {'a' : 'Submit not pressed'}
    return render(request, 'check.html')


def predictHeart(request):
    context = {'a' : 'Submit pressed'}
    #print(request)

    if(request.method == 'POST'):
        tmp = {}
        tmp['age'] = request.POST.get('age')
        tmp['sex'] = request.POST.get('sex')
        tmp['cp'] = request.POST.get('cp')
        tmp['trestbps'] = request.POST.get('trestbps')
        tmp['chol'] = request.POST.get('chol')
        tmp['fbs'] = request.POST.get('fbs')
        tmp['restecg'] = request.POST.get('restecg')
        tmp['thalach'] = request.POST.get('thalach')
        tmp['exang'] = request.POST.get('exang')
        tmp['oldPeak'] = request.POST.get('oldPeak')
        tmp['slope'] = request.POST.get('slope')
        tmp['ca'] = request.POST.get('ca')
        tmp['thal'] = request.POST.get('thal')

    testData = pd.DataFrame({'x':tmp}).transpose()
    filename = "./models/heart.csv"
    data = pd.read_csv(filename)
    data = pd.read_csv(filename)

    data.dropna()
    y = data['target']
    x = data.drop(['target'], axis = 1)

    x_normal = (x - x.mean())/(x.max() - x.min())
    x_train, x_test, y_train, y_test = train_test_split(x_normal, y, train_size = 0.7, test_size = 0.3, random_state = 42)

    model2 = RandomForestClassifier(n_estimators = 200, max_depth = 15, random_state = 0)
    model2.fit(x_train, y_train)
    y_pred2 = model2.predict(x_test)
    prediction = model2.predict(testData)[0]
    context = {'prediction' : prediction}
    return render(request, 'check.html', context)

templates/base.html
{% load static from staticfiles%}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
            rel="stylesheet"
        />
        <title>Welcome</title>
    </head>
    <body class="bg-gray-900">
        <style>
            a:hover {
                cursor: pointer;
                transition: ease 0.35s;
                border: white solid 1px;
                border-radius: 12px;
                padding: 5px;
            }
            a {
                color: white;
            }
        </style>
        <header class="bg-red-500 body-font">
            <div
                class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center"
            >
                <div
                    class="flex title-font font-medium items-center text-white mb-4 md:mb-0"
                >
                    <img
                        id="logo"
                        src="{% static 'heart.png' %}"
                        alt="img"
                        width="40px"
                        height="40px"
                    />
                    <span class="ml-3 text-xl font-bold text-2xl"
                        >Heartify</span
                    >
                </div>
                <nav
                    class="md:ml-auto flex flex-wrap items-center text-base justify-center"
                >
                    <a
                        class="mr-5 hover:text-black text-lg font-semibold"
                        href="{% url 'Home' %}"
                        >Home</a
                    >
                    <a
                        class="mr-5 hover:text-black text-lg font-semibold"
                        href="{% url 'Heart:check' %}"
                        >Check Up</a
                    >
                    <a
                        class="mr-5 hover:text-black text-lg font-semibold"
                        href="{% url 'Contact' %}"
                        >Contact</a
                    >
                </nav>
            </div>
        </header>
        <section class="text-gray-400 body-font">
            <div
                class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center"
            >
                <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 md:mb-0 mb-10">
                    <img
                        class="object-cover object-center rounded"
                        alt="hero"
                        src="{% static 'heart2.png' %}"
                    />
                </div>
                <div
                    class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center"
                >
                    <h1
                        class="title-font sm:text-4xl text-3xl mb-4 font-large text-white font-serif"
                    >
                        Heartify<br />
                        <br class="hidden lg:inline-block" />Your personal Heart
                        Assistant
                    </h1>
                    <p class="mb-8 leading-relaxed font-sans">
                        Heartify is your own personal heart Assistant. Heartify
                        uses Machine Learning to analyse and predict whether you
                        have a heart disease or not. This algorithm is trained
                        against multiple cases so to provide you with correct
                        and accurate prediction.
                    </p>
                    <div class="flex justify-center">
                        <form action="{% url 'Heart:check' %}">
                            <button
                                type="submit"
                                class="inline-flex text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg"
                            >
                                Get Started
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>

templates/check.html
{% load static from staticfiles%}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
            rel="stylesheet"
        />
        <link rel="stylesheet" href="{% static 'check.css' %}" />
        <title>Welcome</title>
    </head>
    <body class="bg-gray-900">
        <style>
            a:hover {
                cursor: pointer;
                transition: ease-out 0.35s;
                border: white solid 1px;
                border-radius: 12px;
                padding: 5px;
            }
            a {
                color: white;
            }
        </style>
        <header class="bg-red-500 body-font">
            <div
                class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center"
            >
                <div
                    class="flex title-font font-medium items-center text-white mb-4 md:mb-0"
                >
                    <img
                        id="logo"
                        src="{% static 'heart.png' %}"
                        alt="img"
                        width="40px"
                        height="40px"
                    />
                    <span class="ml-3 text-xl font-bold text-2xl"
                        >Heartify</span
                    >
                </div>
                <nav
                    class="md:ml-auto flex flex-wrap items-center text-base justify-center"
                >
                    <a
                        class="mr-5 hover:text-black text-lg font-semibold"
                        href="{% url 'Home' %}"
                        >Home</a
                    >
                    <a
                        class="mr-5 hover:text-black text-lg font-semibold"
                        href="{% url 'Heart:check' %}"
                        >Check Up</a
                    >
                    <a
                        class="mr-5 hover:text-black text-lg font-semibold"
                        href="{% url 'Contact' %}"
                        >Contact</a
                    >
                </nav>
            </div>
        </header>
            <div class="flex items-center h-screen w-full bg-teal-lighter">
                <div
                    class="w-full bg-white rounded shadow-lg p-8 m-4 md:max-w-sm md:mx-auto"
                >
                    <h1 class="block w-full text-center text-grey-darkest mb-6 font-bold text-6xl">
                        Heartify
                    </h1>
                    <form
                        class="mb-4 md:flex md:flex-wrap md:justify-between"
                        method="POST"
                        enctype="multipart/form-data"
                        action="{% url 'Heart:predictHeart' %}"
                    >
                        {% csrf_token %}
                        <div class="flex flex-col mb-4 md:w-1/2">
                            <label
                                class="mb-2 uppercase tracking-wide font-bold text-xs text-grey-darkest"
                                for="age"
                                >Age</label
                            >
                            <input
                                class="border py-2 px-3 text-grey-darkest md:mr-2"
                                type="number"
                                name="age"
                                id="age"
                                required
                                placeholder="Ex. 34"
                            />
                        </div>
                        <div class="flex flex-col mb-4 md:w-1/2">
                            <label
                                class="mb-2 uppercase font-bold text-xs text-grey-darkest md:ml-2"
                                for="sex"
                                >Sex</label
                            >
                            <input
                                class="border py-2 px-3 text-grey-darkest md:ml-2"
                                type="number"
                                name="sex"
                                id="sex"
                                required
                                placeholder="M-1 | F-0"
                            />
                        </div>
                        <div class="flex flex-col mb-4 md:w-1/2">
                            <label
                                class="mb-2 uppercase tracking-wide font-bold text-xs text-grey-darkest"
                                for="cp"
                                >Chest Pain Type</label
                            >
                            <input
                                class="border py-2 px-3 text-grey-darkest md:mr-2"
                                type="number"
                                name="cp"
                                id="cp"
                                required
                                placeholder="3/2/1/0"
                            />
                        </div>
                        <div class="flex flex-col mb-4 md:w-1/2">
                            <label
                                class="mb-2 uppercase tracking-wide font-bold text-xs text-grey-darkest"
                                for="trestbps"
                                >Resting BP</label
                            >
                            <input
                                class="border py-2 px-3 text-grey-darkest md:mr-2"
                                type="number"
                                name="trestbps"
                                id="trestbps"
                                required
                                placeholder="Ex. 110"
                            />
                        </div>
                        <div class="flex flex-col mb-4 md:w-1/2">
                            <label
                                class="mb-2 uppercase tracking-wide font-bold text-xs text-grey-darkest"
                                for="chol"
                                >Cholestoral</label
                            >
                            <input
                                class="border py-2 px-3 text-grey-darkest md:mr-2"
                                type="number"
                                name="chol"
                                id="chol"
                                required
                                placeholder="Ex. 210"
                            />
                        </div>
                        <div class="flex flex-col mb-4 md:w-1/2">
                            <label
                                class="mb-2 uppercase tracking-wide font-bold text-xs text-grey-darkest"
                                for="fbs"
                                >Fasting Blood Sugar</label
                            >
                            <input
                                class="border py-2 px-3 text-grey-darkest md:mr-2"
                                type="number"
                                name="fbs"
                                id="fbs"
                                required
                                placeholder=">120 - 1 or 0"
                            />
                        </div>
                        <div class="flex flex-col mb-4 md:w-1/2">
                            <label
                                class="mb-2 uppercase tracking-wide font-bold text-xs text-grey-darkest"
                                for="restecg"
                                >Rest ECG</label
                            >
                            <input
                                class="border py-2 px-3 text-grey-darkest md:mr-2"
                                type="number"
                                name="restecg"
                                id="restecg"
                                required
                                placeholder="0 or 1"
                            />
                        </div>
                        <div class="flex flex-col mb-4 md:w-1/2">
                            <label
                                class="mb-2 uppercase tracking-wide font-bold text-xs text-grey-darkest"
                                for="thalach"
                                >Max. Heart Rate</label
                            >
                            <input
                                class="border py-2 px-3 text-grey-darkest md:mr-2"
                                type="number"
                                name="thalach"
                                id="thalach"
                                required
                                placeholder="Ex. 157"
                            />
                        </div>
                        <div class="flex flex-col mb-4 md:w-1/2">
                            <label
                                class="mb-2 uppercase tracking-wide font-bold text-xs text-grey-darkest"
                                for="exang"
                                >Exercise Angina</label
                            >
                            <input
                                class="border py-2 px-3 text-grey-darkest md:mr-2"
                                type="number"
                                name="exang"
                                id="exang"
                                required
                                placeholder="0 or 1"
                            />
                        </div>
                        <div class="flex flex-col mb-4 md:w-1/2">
                            <label
                                class="mb-2 uppercase tracking-wide font-bold text-xs text-grey-darkest"
                                for="oldPeak"
                                >ST depression</label
                            >
                            <input
                                class="border py-2 px-3 text-grey-darkest md:mr-2"
                                type="number"
                                name="oldPeak"
                                id="oldPeak"
                                required
                                placeholder="Ex. 1.3"
                                min="0" value="0" step="0.1"
                            />
                        </div>
                        <div class="flex flex-col mb-4 md:w-1/2">
                            <label
                                class="mb-2 uppercase tracking-wide font-bold text-xs text-grey-darkest"
                                for="slope"
                                >Slope of ST</label
                            >
                            <input
                                class="border py-2 px-3 text-grey-darkest md:mr-2"
                                type="number"
                                name="slope"
                                id="slope"
                                placeholder="Ex. 1"
                                required
                            />
                        </div>
                        <div class="flex flex-col mb-4 md:w-1/2">
                            <label
                                class="mb-2 uppercase tracking-wide font-bold text-xs text-grey-darkest"
                                for="ca"
                                >CA</label
                            >
                            <input
                                class="border py-2 px-3 text-grey-darkest md:mr-2"
                                type="number"
                                name="ca"
                                id="ca"
                                placeholder="0/1/2/3"
                                required
                            />
                        </div>
                        <div class="flex flex-col mb-6 md:w-full">
                            <label
                                class="mb-2 uppercase font-bold text-xs text-grey-darkest"
                                for="thal"
                                >Thal</label
                            >
                            <input
                                class="border py-2 px-3 text-grey-darkest"
                                type="number"
                                name="thal"
                                id="thal"
                                placeholder="Ex. 0"
                                required
                            />
                        </div>
                        <button type="submit" class="inline-flex place-self-center items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                            Submit
                        </button><br/><br />
                        {% if prediction == 0 %}
                            <br><br><h1 class="block w-full text-center text-grey-darkest mb-6 font-medium text-lg">Yayy, You have no symptoms for a heart disease</h1>
                        {% elif prediction == 1 %}
                            <br><br><h1 class="block w-full text-center text-grey-darkest mb-6 font-medium text-lg">Please consult a Cardiologist</h1>
                        {% endif %}
                        <!-- <input type="submit" value="Submit"/> -->
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

templates/contact.html
{% load static from staticfiles%}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
            rel="stylesheet"
        />
        <link rel="stylesheet" href="{% static 'check.css' %}" />
        <title>Welcome</title>
    </head>
    <body class="bg-gray-900">
        <style>
            a:hover {
                cursor: pointer;
                transition: ease-out 0.35s;
                border: white solid 1px;
                border-radius: 12px;
                padding: 5px;
            }
            a {
                color: white;
            }
        </style>
        <header class="bg-red-500 body-font">
            <div
                class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center"
            >
                <div
                    class="flex title-font font-medium items-center text-white mb-4 md:mb-0"
                >
                    <img
                        id="logo"
                        src="{% static 'heart.png' %}"
                        alt="img"
                        width="40px"
                        height="40px"
                    />
                    <span class="ml-3 text-xl font-bold text-2xl"
                        >Heartify</span
                    >
                </div>
                <nav
                    class="md:ml-auto flex flex-wrap items-center text-base justify-center"
                >
                    <a
                        class="mr-5 hover:text-black text-lg font-semibold"
                        href="{% url 'Home' %}"
                        >Home</a
                    >
                    <a
                        class="mr-5 hover:text-black text-lg font-semibold"
                        href="{% url 'Heart:check' %}"
                        >Check Up</a
                    >
                    <a
                        class="mr-5 hover:text-black text-lg font-semibold"
                        href="{% url 'Contact' %}"
                        >Contact</a
                    >
                </nav>
            </div>
        </header>
        <br /><br />
        <section class="text-gray-400 bg-gray-900 body-font relative">
            <div
                class="container px-5 py-24 mx-auto flex sm:flex-nowrap flex-wrap"
            >
                <div
                    class="lg:w-2/3 md:w-1/2 bg-gray-900 rounded-lg overflow-hidden sm:mr-10 p-10 flex items-end justify-start relative"
                >
                    <iframe
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3753474.038097005!2d76.5864192039492!3d23.261202724507328!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30635ff06b92b791%3A0xd78c4fa1854213a6!2sIndia!5e0!3m2!1sen!2sin!4v1610257388143!5m2!1sen!2sin"
                        width="100%"
                        height="100%"
                        title="map"
                        class="absolute inset-0"
                        frameborder="0"
                        marginheight="0"
                        marginwidth="0"
                        scrolling="no"
                        style="filter: grayscale(1) contrast(1.2) opacity(0.16)"
                    ></iframe>
                    <div
                        class="bg-gray-900 relative flex flex-wrap py-6 rounded shadow-md"
                    >
                        <div class="lg:w-1/2 px-6">
                            <h2
                                class="title-font font-semibold text-white tracking-widest text-xs"
                            >
                                ADDRESS
                            </h2>
                            <p class="mt-1">The Python Week, India</p>
                        </div>
                        <div class="lg:w-1/2 px-6 mt-4 lg:mt-0">
                            <h2
                                class="title-font font-semibold text-white tracking-widest text-xs"
                            >
                                EMAIL
                            </h2>
                            <a class="text-blue-400 leading-relaxed"
                                >pythonWeek@email.com</a
                            >
                            <h2
                                class="title-font font-semibold text-white tracking-widest text-xs mt-4"
                            >
                                PHONE
                            </h2>
                            <p class="leading-relaxed">123-456-7890</p>
                        </div>
                    </div>
                </div>
                <div
                    class="lg:w-1/3 md:w-1/2 flex flex-col md:ml-auto w-full md:py-8 mt-8 md:mt-0"
                >
                    <h2 class="text-white text-lg mb-1 font-medium title-font">
                        Feedback
                    </h2>
                    <p class="leading-relaxed mb-5">
                        Good or Bad , It's a Feedback
                    </p>
                    <div class="relative mb-4">
                        <label
                            for="name"
                            class="leading-7 text-sm text-gray-400"
                            >Name</label
                        >
                        <input
                            type="text"
                            id="name"
                            name="name"
                            class="w-full bg-gray-800 rounded border border-gray-700 focus:border-blue-500 focus:ring-2 focus:ring-blue-900 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
                        />
                    </div>
                    <div class="relative mb-4">
                        <label
                            for="email"
                            class="leading-7 text-sm text-gray-400"
                            >Email</label
                        >
                        <input
                            type="email"
                            id="email"
                            name="email"
                            class="w-full bg-gray-800 rounded border border-gray-700 focus:border-blue-500 focus:ring-2 focus:ring-blue-900 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
                        />
                    </div>
                    <div class="relative mb-4">
                        <label
                            for="message"
                            class="leading-7 text-sm text-gray-400"
                            >Message</label
                        >
                        <textarea
                            id="message"
                            name="message"
                            class="w-full bg-gray-800 rounded border border-gray-700 focus:border-blue-500 focus:ring-2 focus:ring-blue-900 h-32 text-base outline-none text-gray-100 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out"
                        ></textarea>
                    </div>
                    <button
                        class="text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg"
                    >
                        Button
                    </button>
                    <p class="text-xs text-gray-400 text-opacity-90 mt-3">
                        Currently Feedback form is under construction.<br />
                        Thank you for your patience.
                    </p>
                </div>
            </div>
        </section>
    </body>
</html>